# Generated by Django 3.2 on 2022-11-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'charge station', 'verbose_name_plural': 'charge stations'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='token',
            field=models.CharField(help_text='<a onclick="GenerateToken()">Generate new</a><script>function GenerateToken() {const symbols = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";let token = "api-insecure-";for (let i = 0; i < 18; i++) {token += symbols[Math.floor(Math.random() * symbols.length)];if (i == 6) {token += "-"}}document.getElementById("id_token").value = token;}GenerateToken()</script>', max_length=16, unique=True, verbose_name='API Token'),
        ),
        migrations.AlterField(
            model_name='station',
            name='charging',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.flight', verbose_name='Flight'),
        ),
        migrations.AlterField(
            model_name='station',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.IntegerField(choices=[(0, 'Closed'), (1, 'Closing'), (2, 'Opening'), (3, 'Opened')], default=0, verbose_name='Station status'),
        ),
        migrations.AlterField(
            model_name='station',
            name='token',
            field=models.CharField(help_text='<a onclick="GenerateToken()">Generate new</a><script>function GenerateToken() {const symbols = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";let token = "api-insecure-";for (let i = 0; i < 18; i++) {token += symbols[Math.floor(Math.random() * symbols.length)];if (i == 6) {token += "-"}}document.getElementById("id_token").value = token;}GenerateToken()</script>', max_length=16, unique=True, verbose_name='API Token'),
        ),
    ]
