# Generated by Django 3.2 on 2022-11-26 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20221126_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='token',
            field=models.CharField(help_text='<a onclick="GenerateToken()">Generate new</a><script>function GenerateToken() {const symbols = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";let token = "api-insecure-";for (let i = 0; i < 18; i++) {token += symbols[Math.floor(Math.random() * symbols.length)];if (i == 6) token += "-";}document.getElementById("id_token").value = token;}if (!document.getElementById("id_token").value) GenerateToken();</script>', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(regex='api-insecure-[a-zA-Z0-9]{7}-[a-zA-Z0-9]{11}')], verbose_name='API Token'),
        ),
        migrations.AlterField(
            model_name='station',
            name='token',
            field=models.CharField(help_text='<a onclick="GenerateToken()">Generate new</a><script>function GenerateToken() {const symbols = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";let token = "api-insecure-";for (let i = 0; i < 18; i++) {token += symbols[Math.floor(Math.random() * symbols.length)];if (i == 6) token += "-";}document.getElementById("id_token").value = token;}if (!document.getElementById("id_token").value) GenerateToken();</script>', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(regex='api-insecure-[a-zA-Z0-9]{7}-[a-zA-Z0-9]{11}')], verbose_name='API Token'),
        ),
    ]
