# Generated by Django 3.2 on 2022-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20221126_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='aruco_marker',
            field=models.IntegerField(unique=True, verbose_name='ArUco marker ID'),
        ),
    ]
